import 'dotenv/config';
import { GoogleGenAI } from '@google/genai';

const API_KEY = process.env.GOOGLE_AI_KEY;

if (!API_KEY) {
    throw new Error('GOOGLE_AI_KEY is missing in .env');
}

const ai = new GoogleGenAI({
    apiKey: API_KEY
});

const MODEL_NAMES = [
    'gemini-3.6-flash',
    'gemini-3.5-flash',
    'gemini-3.1-flash-lite',
    'gemini-2.5-flash'
];

const SYSTEM_INSTRUCTION = `
You are CodeSync AI, an expert full-stack developer. You work like Google AI Studio - generate complete, runnable projects based on user prompts.

🚨 CRITICAL RULES:

1. **FLAT FILE STRUCTURE ONLY** - WebContainer does NOT support nested folders. ALL files at ROOT level.
   - ✅ package.json (root)
   - ✅ server.js (root)
   - ✅ index.html (root)
   - ✅ main.jsx (root)
   - ✅ App.jsx (root)
   - ❌ NO src/ folder
   - ❌ NO public/ folder

2. **For React + Vite projects:**
   - index.html: <script type="module" src="/main.jsx"></script>
   - main.jsx: import App from './App.jsx'
   - All files at root level

3. **For Node.js + Express projects:**
   - server.js with proper routes
   - package.json with express dependency
   - Root route "/" must exist

4. **Return ONLY valid JSON with this structure:**
   {
     "text": "Friendly explanation of what was generated",
     "fileTree": {
       "package.json": { "file": { "contents": "..." } },
       "server.js": { "file": { "contents": "..." } },
       "index.html": { "file": { "contents": "..." } }
     },
     "buildCommand": { "mainItem": "npm", "commands": ["install"] },
     "startCommand": { "mainItem": "npm", "commands": ["start"] }
   }

5. **Be conversational and helpful** - like Google AI Studio.

6. **Escape all JSON strings correctly.**
`;

function safeJsonParse(text) {
    if (!text || typeof text !== 'string') {
        throw new Error('AI returned an empty response');
    }

    const trimmed = text.trim();

    try {
        return JSON.parse(trimmed);
    } catch {}

    const cleaned = trimmed
        .replace(/^```json\s*/i, '')
        .replace(/^```\s*/i, '')
        .replace(/\s*```$/i, '')
        .trim();

    try {
        return JSON.parse(cleaned);
    } catch {}

    const start = cleaned.indexOf('{');

    if (start === -1) {
        throw new Error('AI response does not contain JSON');
    }

    let depth = 0;
    let inString = false;
    let escaped = false;

    for (let i = start; i < cleaned.length; i++) {
        const char = cleaned[i];

        if (escaped) {
            escaped = false;
            continue;
        }

        if (char === '\\') {
            escaped = true;
            continue;
        }

        if (char === '"') {
            inString = !inString;
            continue;
        }

        if (inString) continue;

        if (char === '{') depth++;

        if (char === '}') {
            depth--;

            if (depth === 0) {
                return JSON.parse(cleaned.slice(start, i + 1));
            }
        }
    }

    throw new Error('AI returned incomplete JSON');
}

function validateFileTree(tree) {
    if (!tree || typeof tree !== 'object' || Array.isArray(tree)) {
        return false;
    }

    let fileCount = 0;
    let valid = true;

    function walk(node) {
        for (const value of Object.values(node)) {
            if (!value || typeof value !== 'object') {
                valid = false;
                continue;
            }

            if (value.file) {
                if (typeof value.file.contents !== 'string') {
                    valid = false;
                } else {
                    fileCount++;
                }
                continue;
            }

            walk(value);
        }
    }

    walk(tree);

    return valid && fileCount > 0;
}

// ─── Project Generation ──────────────────────────────────────────────────────
export const generateResult = async (prompt) => {
    if (!prompt || typeof prompt !== 'string' || !prompt.trim()) {
        throw new Error('Prompt is required');
    }

    let lastError;

    for (const modelName of MODEL_NAMES) {
        try {
            console.log(`🤖 Trying AI model: ${modelName}`);

            const response = await ai.models.generateContent({
                model: modelName,
                contents: prompt.trim(),
                config: {
                    systemInstruction: SYSTEM_INSTRUCTION,
                    temperature: 0.7,
                    maxOutputTokens: 8192,
                    responseMimeType: 'application/json'
                }
            });

            const text = response.text;

            if (!text) {
                throw new Error('Empty response from Gemini');
            }

            const result = safeJsonParse(text);

            if (!result.fileTree || !validateFileTree(result.fileTree)) {
                throw new Error('Invalid file tree generated by AI');
            }

            result.text ??= 'Project generated successfully.';
            result.buildCommand ??= {
                mainItem: 'npm',
                commands: ['install']
            };
            result.startCommand ??= {
                mainItem: 'npm',
                commands: ['start']
            };

            console.log(`✅ Success with ${modelName}`);

            return result;

        } catch (error) {
            lastError = error;

            console.error(
                `❌ ${modelName} failed:`,
                error.message
            );

            const message = error.message?.toLowerCase() || '';

            if (
                message.includes('404') ||
                message.includes('not found') ||
                message.includes('not_found')
            ) {
                console.log(`⏭️ Trying next model...`);
                continue;
            }

            if (
                message.includes('api key') ||
                message.includes('401') ||
                message.includes('quota')
            ) {
                console.log(`⏭️ API key issue or quota exceeded, trying next model...`);
                continue;
            }
        }
    }

    console.warn('⚠️ All AI models failed, returning fallback project');
    return getFallbackProject(lastError?.message);
};

// ─── AI Chat ──────────────────────────────────────────────────────────────────
export const chatWithAI = async (message, history = []) => {
    if (!message || typeof message !== 'string' || !message.trim()) {
        throw new Error('Message is required');
    }

    const chatHistory = history.map(h => ({
        role: h.role || 'user',
        parts: [{ text: h.content || h.text || '' }]
    }));

    const fullPrompt = `
You are CodeSync AI, an expert developer assistant. You work like Google AI Studio - helpful, conversational, and informative.

Previous conversation:
${chatHistory.map(h => `${h.role}: ${h.parts[0].text}`).join('\n')}

User: ${message.trim()}

Respond in a helpful, conversational way. Keep responses concise but informative. Be like Google AI Studio - friendly and knowledgeable.
`;

    let lastError;

    for (const modelName of MODEL_NAMES) {
        try {
            console.log(`💬 Trying AI model for chat: ${modelName}`);

            const response = await ai.models.generateContent({
                model: modelName,
                contents: fullPrompt,
                config: {
                    temperature: 0.7,
                    maxOutputTokens: 1024,
                }
            });

            const text = response.text;

            if (!text) {
                throw new Error('Empty response from Gemini');
            }

            console.log(`✅ Chat success with ${modelName}`);
            return { text: text.trim() };

        } catch (error) {
            lastError = error;
            console.error(`❌ ${modelName} chat failed:`, error.message);

            const messageLower = error.message?.toLowerCase() || '';

            if (
                messageLower.includes('404') ||
                messageLower.includes('not found') ||
                messageLower.includes('not_found') ||
                messageLower.includes('quota')
            ) {
                console.log(`⏭️ Trying next model...`);
                continue;
            }

            if (
                messageLower.includes('api key') ||
                messageLower.includes('401')
            ) {
                console.log(`⏭️ API key issue, trying next model...`);
                continue;
            }
        }
    }

    console.warn('⚠️ All AI models failed for chat, returning fallback');
    return {
        text: "I'm having trouble connecting to my AI services right now. Please try again in a moment."
    };
};

// ─── Fallback Project ────────────────────────────────────────────────────────
function getFallbackProject(errorMessage) {
    return {
        text: errorMessage 
            ? `⚠️ AI Error: ${errorMessage}. Using fallback template.` 
            : 'Generated with fallback template',
        fileTree: {
            'package.json': {
                file: {
                    contents: JSON.stringify({
                        name: 'my-app',
                        version: '1.0.0',
                        type: 'module',
                        scripts: {
                            dev: 'vite',
                            build: 'vite build',
                            start: 'vite preview'
                        },
                        dependencies: {
                            'react': '^18.2.0',
                            'react-dom': '^18.2.0'
                        },
                        devDependencies: {
                            '@vitejs/plugin-react': '^4.0.0',
                            'vite': '^4.3.9'
                        }
                    }, null, 2)
                }
            },
            'vite.config.js': {
                file: {
                    contents: `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n});`
                }
            },
            'index.html': {
                file: {
                    contents: `<!DOCTYPE html>\n<html>\n<head>\n  <title>My App</title>\n</head>\n<body>\n  <div id="root"></div>\n  <script type="module" src="/main.jsx"></script>\n</body>\n</html>`
                }
            },
            'main.jsx': {
                file: {
                    contents: `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App.jsx';\n\nReactDOM.createRoot(document.getElementById('root')).render(<App />);`
                }
            },
            'App.jsx': {
                file: {
                    contents: `import { useState } from 'react';\n\nfunction App() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div style={{ textAlign: 'center', padding: '50px', fontFamily: 'system-ui' }}>\n      <h1 style={{ color: '#60a5fa' }}>🚀 CodeSync</h1>\n      <p style={{ color: '#94a3b8' }}>Your project is running!</p>\n      <button \n        onClick={() => setCount(count + 1)}\n        style={{ padding: '12px 24px', background: '#3b82f6', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontSize: '16px' }}\n      >\n        Clicked {count} times\n      </button>\n    </div>\n  );\n}\n\nexport default App;`
                }
            }
        },
        buildCommand: { mainItem: 'npm', commands: ['install'] },
        startCommand: { mainItem: 'npm', commands: ['start'] }
    };
}

export default generateResult;