import express from 'express';
import { generateResult, chatWithAI } from '../services/ai.service.js';

const router = express.Router();

// Project Generation Route
router.post('/generate-project', async (req, res) => {
    try {
        const { prompt } = req.body;

        if (!prompt || typeof prompt !== 'string' || !prompt.trim()) {
            return res.status(400).json({
                success: false,
                message: 'Prompt is required'
            });
        }

        console.log('🤖 AI project generation request received');

        const result = await generateResult(prompt.trim());

        return res.status(200).json({
            success: true,
            message: 'Project generated successfully',
            project: {
                fileTree: result.fileTree || {},
                _id: req.body.projectId || 'new-project'
            },
            ai: {
                text: result.text || 'Project generated successfully!',
                fileTree: result.fileTree || {},
                buildCommand: result.buildCommand || { mainItem: 'npm', commands: ['install'] },
                startCommand: result.startCommand || { mainItem: 'npm', commands: ['start'] }
            },
            data: result
        });

    } catch (error) {
        console.error('❌ AI Generation Route Error:', error.message);

        const fallbackTree = {
            'index.js': {
                file: {
                    contents: 'console.log("Hello from CodeSync!");'
                }
            },
            'package.json': {
                file: {
                    contents: JSON.stringify({
                        name: 'fallback-project',
                        version: '1.0.0',
                        scripts: {
                            start: 'node index.js'
                        }
                    }, null, 2)
                }
            },
            'README.md': {
                file: {
                    contents: '# Fallback Project\n\nGenerated by CodeSync AI fallback.'
                }
            }
        };

        return res.status(200).json({
            success: false,
            message: error.message || 'Failed to generate project, using fallback',
            project: {
                fileTree: fallbackTree,
                _id: req.body.projectId || 'fallback'
            },
            ai: {
                text: '⚠️ AI generation failed. Using fallback template.',
                fileTree: fallbackTree,
                buildCommand: { mainItem: 'npm', commands: ['install'] },
                startCommand: { mainItem: 'npm', commands: ['start'] }
            }
        });
    }
});

// ✅ AI Chat Route
router.post('/chat', async (req, res) => {
    try {
        const { message, history } = req.body;

        if (!message || typeof message !== 'string' || !message.trim()) {
            return res.status(400).json({
                success: false,
                message: 'Message is required'
            });
        }

        console.log('💬 AI Chat request received');

        const result = await chatWithAI(message.trim(), history || []);

        return res.status(200).json({
            success: true,
            message: 'AI response generated',
            data: result
        });

    } catch (error) {
        console.error('❌ AI Chat Error:', error.message);

        return res.status(200).json({
            success: false,
            message: error.message || 'Failed to generate AI response',
            data: {
                text: '⚠️ Sorry, I encountered an error. Please try again.'
            }
        });
    }
});

export default router;